version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  
  describe_plot_age_distribution:
    run: r:latest analysis/plotting_age.r
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        plot1: output/descriptive.png
        plot2: output/descriptive_region.png

  describe_table_eth_sex:
    run: r:latest analysis/table_ethnicity_by_sex.r
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        tab1: output/tab_ethSex.csv