version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  
  describe:
    run: r:latest analysis/plotting_age.r
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        plot1: output/descriptive.png
